#!/usr/bin/python3
"""Alta3 APIs and HTML"""

## best practice says don't use commas in imports
# use a single line for each import
from flask import Flask
from flask import redirect
from flask import url_for
from flask import request
from flask import render_template

app = Flask(__name__)
## This is where we want to redirect users to
@app.route("/success/")
def success():
    return f"You didn't end up in the gorge of eternal peril!\n"
# This is a landing point for users (a start)
@app.route("/") # user can land at "/"
def start():
    return render_template("quiz.html") # look for templates/postmaker.html
# This is where postmaker.html POSTs data to
# A user could also browser (GET) to this location
@app.route("/answer", methods = ["POST", "GET"])
def login():
    # POST would likely come from a user interacting with postmaker.html
    if request.method == "POST":
        if request.form.get("nm"): # if nm was assigned via the POST
            if "to seek the holy grail" in request.form.get("nm").lower():  # grab the value of nm from the POST
                return redirect(url_for("success"))
    # GET would likely come from a user interacting with a browser
    elif request.method == "GET":
        if request.args.get("nm"): # if nm was assigned as a parameter=value
            if "to seek the holy grail" in request.args.get("nm").lower(): # pull nm from localhost:5060/login?nm=larry
                return redirect(url_for("success"))
    return redirect(url_for("start")) # pass back to /success with val for name
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=2224) # runs the application
